User Interface
rosen-bridge/rosen-sdk pull request #1
Opened 2024-05-29 21:29 UTC by kii-dot

Implementation of Rosen User Interface

2024-06-10 20:19 UTC, RaaCT0R requested changes

2024-06-10 20:19 UTC, RaaCT0R commented on docs/chains/chains.md
remove this file?

2024-06-10 20:19 UTC, RaaCT0R commented on loen-config.json
Please remove any config file (will comment on all of them) since these configs may be updated and should be fetched from contract repo in application, not SDK.

2024-06-10 20:19 UTC, RaaCT0R commented on docs/user-interface.md
remove this file (it is duplicate of README). or keep this file and keep README empty for SDK examples and how to use.

2024-06-10 20:19 UTC, RaaCT0R commented on minimumFee.json
remove this file (it is a config file)

2024-06-10 20:19 UTC, RaaCT0R commented on package.json
> +    "start": "node --experimental-specifier-resolution=node dist/src/index.js",
Please remove `start` script. Packages don't need it.

2024-06-10 20:19 UTC, RaaCT0R commented on package.json
> +    "ergo-lib-wasm-nodejs": "^0.24.0"
Use version `^0.24.1` which is used in all of Rosen packages.

There was multiple cases where version difference caused unexpected behavior.

2024-06-10 20:19 UTC, RaaCT0R commented on src/config.json
remove this file (it is a config file)

2024-06-10 20:19 UTC, RaaCT0R commented on src/constants/constants.ts
config variables such as TOKEN_ID and ADDRESS should be removed.

Also I don't see any use-case related to SDK for TX_URL.

2024-06-10 20:19 UTC, RaaCT0R commented on src/utils/txUrls.ts
Please remove this file. It is irrelevant to Rosen SDK and should be implemented in application itself if is necessary.

2024-06-10 20:19 UTC, RaaCT0R commented on src/userInterface/userInterface.ts
> +    const destChainToken = chains[targetChain];
token may not be supported on the target chain. 

add a check here
> If the target chain is not on the list of its keys, throw an error

2024-06-10 20:19 UTC, RaaCT0R commented on src/userInterface/userInterface.ts
> +        : 1n;
`feesinfo` is always defined. this (and following) conditional operation is redundant.

2024-06-10 20:19 UTC, RaaCT0R commented on src/userInterface/userInterface.ts
> +      throw new FeeRetrievalFailureException("Fetch Minimum fee box failed");
I suggest adding `tokenId` to Error for better debugging.

```suggestion
      throw new FeeRetrievalFailureException(`Failed to fetch Minimum fee box for token [${tokenId}]`);
```

2024-06-10 20:19 UTC, RaaCT0R commented on src/userInterface/userInterface.ts
> +      explorerUrl,
`url` should also be specified in constructor alongside `ergoNetworkType`.

2024-06-10 20:19 UTC, RaaCT0R commented on tests/rosenUserInterface.test.ts
> +    checkChainSupportedTokensMetadataType("cardano", "ADA", TokenType.CIP26);
Tokens are not forced to be EIP004 or CIP26. therefore this check is wrong.

2024-06-10 20:19 UTC, RaaCT0R commented on tests/rosenUserInterface.test.ts
> +  it("getAvailableChainsForToken", () => {
a non multi chain check is necessary for this test. I suggest to run the test for `RSN` and `BTC` where `BTC` exists on all 3 chains (ergo, cardano and bitcoin) but `RSN` only exists on ergo and cardano.

2024-06-10 20:19 UTC, RaaCT0R commented on tests/rosenUserInterface.test.ts
> +  });
tests should not interact with blockchain.

For this and next tests, you need to mock `MinimumFeeBox` behvaior.

2024-06-10 20:19 UTC, RaaCT0R commented on src/types/tokensType.ts
Please remove this file. Types should be used directly from `@rosen-bridge/tokens` package as they may change. Although they are a little ambiguous, the exact type should be unnecessary for now.

2024-06-10 20:19 UTC, RaaCT0R commented on src/types/cardanoTypes.ts
Please move this file under `chains` directory as they are chain-specific types.

2024-06-10 20:19 UTC, RaaCT0R commented on src/types/chainTypes.ts
Please move this file under `chains` directory, as the `RosenChain` class itself is there.

(Also I suggest putting it in the same file as `RosenChain` since you did this for `UserInterface` class)

2024-06-10 20:19 UTC, RaaCT0R commented on src/config/RosenSDKConfig.ts
> +};
Please remove `DefaultRosenSDKConfig` and `LoenRosenSDKConfig` as they are irrelevant to SDK and should be defined in application itself.

2024-06-10 21:55 UTC, kii-dot commented on tests/rosenUserInterface.test.ts
> +    checkChainSupportedTokensMetadataType("cardano", "ADA", TokenType.CIP26);
the tests takes the metadatatype and checks it. It does not necessarily state that the token has to be of a certain EIP or CIP. Thats why it is input as an argument

2024-06-11 07:08 UTC, kii-dot commented on src/userInterface/userInterface.ts
> +      explorerUrl,
updated in next commit

2024-06-11 07:27 UTC, kii-dot commented on tests/rosenUserInterface.test.ts
> +  });
I thought about writing it, however, I havent had the right idea on how to inject. Will work on this in next pr #2

2024-06-11 09:49 UTC, RaaCT0R commented on src/userInterface/userInterface.ts
> +
accessing unknown key of the object returns `undefined`, therefore this check is not working. Please proceed as you did in `checkTokenSupported` function (using `TokenMap.getID` and try-catch`)

2024-06-11 18:19 UTC, RaaCT0R approved these changes

2024-06-12 05:34 UTC, merged