Chains: Cardano and Ergo Impl
rosen-bridge/rosen-sdk pull request #3
Opened 2024-06-13 23:31 UTC by kii-dot

Cardano and Ergo chain impl for bridging

2024-06-19 19:13 UTC, RaaCT0R requested changes

2024-06-19 19:13 UTC, RaaCT0R commented on README.md
> +npx @rosen-bridge/cli download-assets --include-prereleases --chain-type loen --out some/download/path
Don't use `loen` for example.

Also no prereleases I guess.

```suggestion
npx @rosen-bridge/cli download-assets --chain-type public-launch --out some/download/path
```

2024-06-19 19:13 UTC, RaaCT0R commented on README.md
> +Please download the appropriate files for your project, ensuring you select the latest prerelease version rather than a stable release. This will ensure you have the most up-to-date features and impr
I'm not sure about this. It may include breaking-change and usually it takes a while to reach production. I wouldn't recommend using prereleases unless they know what they're doing.

2024-06-19 19:13 UTC, RaaCT0R commented on src/chains/cardano/cardanoChain.ts
> +  static getBaseNetworkFee(): bigint {
`getBaseNetworkFee` need to be async in some chains (such as Bitcoin and EVM). So, define it async in `IRosenChain` and all of the chains.

2024-06-19 19:13 UTC, RaaCT0R commented on src/chains/cardano/cardanoChain.ts
> +@staticImplements<IRosenChain>()
What is the reason for using such decorator, instead of simply extending an abstract class? I mean, what is the purpose of using IRosenChain interface (in combination of a decorator) instead of say, an AbstractRosenChain class?

Also consider that decorators are not part of ECMAScript standard yet.

2024-06-19 19:13 UTC, RaaCT0R commented on src/chains/cardano/cardanoSDK.ts
> +    fromAddressHex: string,
it should be `fromAddress` in bech32 format, which is used everywhere.

We used hex in UI because of some server/client side issue, which is not the case in SDK

_(Note that type still remain string, but usage is different. Also it's good to mention things like this in param description in doc string)_

2024-06-19 19:13 UTC, RaaCT0R commented on src/chains/cardano/cardanoSDK.ts
> +    changeAddressHex: string,
same as `fromAddress`, it should be in bech32 format, which is used everywhere.

2024-06-19 19:13 UTC, RaaCT0R commented on src/chains/ergo/ergoSDK.ts
> +  private static async getCoveringBoxes(
Please remove this function and use `@rosen-bridge/ergo-box-selection` package instead.

2024-06-19 19:13 UTC, RaaCT0R commented on package.json
> +    "@rosen-chains/abstract-chain": "^7.0.2",
what is usage of `observation-extractor` and `abstract-chain`??

2024-06-20 19:33 UTC, RaaCT0R commented on src/chains/chains.ts
>          return CardanoRosenChain.getBaseNetworkFee();
add `await` for Ergo and Cardano too?

2024-06-21 08:45 UTC, kii-dot commented on src/chains/chains.ts
>          return CardanoRosenChain.getBaseNetworkFee();
if its a constant, there dont need to be await

2024-06-24 18:38 UTC, RaaCT0R approved these changes

2024-06-24 18:39 UTC, merged